# Generated by Django 5.2.11 on 2026-02-20 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_recreate_missing_personal_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="iso_code",
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="personalactor",
            name="poster_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="posters/actors/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="personalmovie",
            name="poster_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="posters/movies/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="personalactor",
            name="poster_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="personalmovie",
            name="poster_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]