# Generated by Django 5.2.11 on 2026-02-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
